In [1]:

import pandas as pd

titanic_df = pd.read_csv(
    r"C:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\Skill_Sikshya\Day22\titanic_data.csv",
    delimiter = ",",
    header = 0
    )

titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:

#isna()

null_cabin = titanic_df[titanic_df.Cabin.isna()]

print(null_cabin.head())

   PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male
2            3         1       3          Heikkinen, Miss. Laina  female
4            5         0       3        Allen, Mr. William Henry    male
5            6         0       3                Moran, Mr. James    male
7            8         0       3  Palsson, Master. Gosta Leonard    male

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  22.0      1      0         A/5 21171   7.2500   NaN        S
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
4  35.0      0      0            373450   8.0500   NaN        S
5   NaN      0      0            330877   8.4583   NaN        Q
7   2.0      3      1            349909  21.0750   NaN        S

In [6]:
null_cabin.shape

(687, 12)

In [3]:
titanic_df.Cabin.isna().sum()

np.int64(687)

In [7]:
#notna()
non_empty_cabin = titanic_df[titanic_df.Cabin.notna()]
non_empty_cabin.shape

(204, 12)

In [ ]:
# Duplicate Data
# titanic_df["Ticket"].duplicated().shape
duplicate_ticket = titanic_df[titanic_df.duplicated(subset = "Ticket", keep = "first")]
duplicate_ticket.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.075,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.900,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.000,C23 C25 C27,S
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.000,NaN,S
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.275,NaN,S

In [18]:
titanic_df[titanic_df.Ticket == "19950"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0,C23 C25 C27,S

In [19]:
duplicate_ticket = titanic_df[titanic_df.duplicated()]
duplicate_ticket

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [21]:
# isin , where
titanic_df[titanic_df.Name.isin(["Fortune, Mr. Charles Alexander"])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0,C23 C25 C27,S

In [24]:
# where
# mask
titanic_df.Age.where(titanic_df.Age > 0 , other = 1 )

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     1.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [26]:
titanic_df.Age.mask(titanic_df.Age < 0 , other = 1 )

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

Filter Using index

In [29]:
titanic_df.loc[:10 ,[ "Name", "Age"]]

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0

In [30]:
titanic_df.iloc[:10, 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: str

In [36]:
titanic_df.loc[890, ["Name", "Age"]]

Name    Dooley, Mr. Patrick
Age                    32.0
Name: 890, dtype: object

In [41]:
titanic_df.at[1, "Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'