In [1]:
import pandas as pd
import seaborn as sns

titanic_df = pd.read_csv(
    r"C:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\Skill_Sikshya\Day22\titanic_data.csv",
    delimiter = ",",
    header = 0
    )

titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Data Encoding
Data Encoding is the process of converting categorical or non-numerical data into a numerical format so that Machine Learning algorithms can understand and process it.

Common encoding techniques include:

Label Encoding
One-Hot Encoding
Ordinal Encoding
Binary Encoding
Frequency Encoding
Target Encoding
Count Encoding

In [ ]:
# Nominal and Ordinal Data

In [ ]:
One Hot Encoding

In [5]:
# Pandas
pd.get_dummies(titanic_df, columns = ["Sex","Embarked"], dtype = int).head(5)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,0,1,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,1,0,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,0,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,1,0,0,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,0,1,0,0,1

In [7]:
import sklearn
sklearn.show_versions()

System:
    python: 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)]
executable: c:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\.venv\Scripts\python.exe
   machine: Windows-11-10.0.26200-SP0

Python dependencies:
      sklearn: 1.9.0
          pip: 26.2.1
   setuptools: None
        numpy: 2.5.2
        scipy: 1.18.0
       Cython: None
       pandas: 3.0.5
   matplotlib: 3.11.1
       joblib: 1.5.3
threadpoolctl: 3.6.0
     narwhals: 2.25.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libscipy_openblas
       filepath: C:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\.venv\Lib\site-packages\numpy.libs\libscipy_openblas64_-327b2e0bcffce2882e0dc04cdeb4eaa6.dll
        version: 0.3.34.0.0
threading_layer: pthreads
   architecture: SkylakeX

       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libscipy_openblas
       filepath: C:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\.venv\Lib\site-packages\scipy.libs\libscipy_openblas-197ee2fc9b4d071f7e048078cac74115.dll
        version: 0.3.31.dev
threading_layer: pthreads
   architecture: SkylakeX

       user_api: openmp
   internal_api: openmp
    num_threads: 8
         prefix: vcomp
       filepath: C:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\.venv\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None