In [1]:
import pandas as pd

df1 = pd.DataFrame(
    {"acc" : [13,33,44,56], "name" : ["Ram", "Shyam", "Hari", "Krishna"], "age" : [24,25,23,24]}
)

df2 = pd.DataFrame(
    {"acc" : [22,34,45,46], "principle" : [400,400,500,600], "interest" : [6.4, 5.6,4.5,8.9]}
)

In [2]:
df1 , df2

(   acc     name  age
 0   13      Ram   24
 1   33    Shyam   25
 2   44     Hari   23
 3   56  Krishna   24,
    acc  principle  interest
 0   22        400       6.4
 1   34        400       5.6
 2   45        500       4.5
 3   46        600       8.9)

concatination

In [3]:
pd.concat([df1,df2], axis = 0, ignore_index = True)

   acc     name   age  principle  interest
0   13      Ram  24.0        NaN       NaN
1   33    Shyam  25.0        NaN       NaN
2   44     Hari  23.0        NaN       NaN
3   56  Krishna  24.0        NaN       NaN
4   22      NaN   NaN      400.0       6.4
5   34      NaN   NaN      400.0       5.6
6   45      NaN   NaN      500.0       4.5
7   46      NaN   NaN      600.0       8.9

Merging

In [6]:
import pandas as pd

df1 = pd.DataFrame(
    {"Key" : ["AB", "CD", "EF","AC"], "name" : ["Ram", "Shyam", "Hari", "Krishna"], "age" : [24,25,23,24]}
)

df2 = pd.DataFrame(
    {"Key" : ["AB","BD","CB","FE"], "principle" : [400,400,500,600], "interest" : [6.4, 5.6,4.5,8.9]}
)

In [7]:
df1, df2

(  Key     name  age
 0  AB      Ram   24
 1  CD    Shyam   25
 2  EF     Hari   23
 3  AC  Krishna   24,
   Key  principle  interest
 0  AB        400       6.4
 1  BD        400       5.6
 2  CB        500       4.5
 3  FE        600       8.9)

In [10]:
pd.merge(df1,df2, how = "right", on = "Key")

  Key name   age  principle  interest
0  AB  Ram  24.0        400       6.4
1  BD  NaN   NaN        400       5.6
2  CB  NaN   NaN        500       4.5
3  FE  NaN   NaN        600       8.9